version: '3'

tasks:
  dev:
    aliases:
      - dev
    desc: 'run sso app with local config'
    cmds:
      - go run ./cmd/sso --config=./config/local.yaml

  create_migration:
    aliases:
      - 'migration create'
    desc: 'create a new SQL migration'
    vars:
      FILE_NAME: '{{.FILE_NAME}}'
    cmds:
      - goose -dir db/migrations create {{.FILE_NAME}} sql

  migrate_up:
    aliases:
      - 'migrate up'
    desc: 'apply all available migrations'
    cmds:
      - goose -dir db/migrations up

  migrate_down:
    aliases:
      - 'migrate down'
    desc: 'roll back migrations to a specific version'
    vars:
      VERSION: '{{.VERSION}}'
    cmds:
      - goose -dir db/migrations down-to {{.VERSION}}