package generator

import "encoding/base64"

// requestURNPrefix is the prefix for OAuth request URIs as per the Internet Engineering Task Force (IETF) parameters.
const requestURNPrefix = "urn:ietf:params:oauth:request_uri:"

// requestURILength is the standard length of the request URI generated by the server for Pushed Authorization Requests (PAR).
const requestURILength = 64

func RequestURI() string {
	randomSymbols := randomBytes(requestURILength)
	urlEncodedString := base64.RawURLEncoding.EncodeToString(randomSymbols)
	requestURI := requestURNPrefix + urlEncodedString

	return requestURI
}
